# Generated by Django 4.0.6 on 2022-07-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_room', models.PositiveIntegerField(default=0)),
                ('room_price', models.PositiveIntegerField(default=0)),
                ('area_of_room', models.CharField(max_length=45)),
                ('floor', models.CharField(max_length=45)),
                ('parking', models.BooleanField(choices=[('yes', 'yes'), ('no', 'no')], default=False)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('description', models.TextField(blank=True, null=True)),
                ('map_link', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
