# Generated by Django 3.2.13 on 2022-07-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_room', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('available_rooms', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('room_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('area_of_room', models.CharField(blank=True, max_length=45, null=True)),
                ('floor', models.CharField(blank=True, max_length=45, null=True)),
                ('parking', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('description', models.TextField(blank=True, null=True)),
                ('map_link', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(blank=True, max_length=3000, null=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.PositiveIntegerField(default=0)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online Pay'), ('offline', 'Offline Pay')], default='offline', max_length=15, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('book_status', models.CharField(choices=[('booked', 'booked'), ('pending', 'pending'), ('cancel', 'cancel')], default='pending', max_length=15)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_booking', to='accounts.customuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_booking', to='rooms.room')),
            ],
        ),
    ]
