# Generated by Django 4.0.6 on 2022-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
