# Generated by Django 4.0.6 on 2022-07-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_email_remove_customuser_first_name_and_more'),
        ('rooms', '0002_alter_room_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.PositiveIntegerField(default=0)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online Pay'), ('offline', 'Offline Pay')], default='offline', max_length=15)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('book_status', models.CharField(choices=[('reserved', 'reserved'), ('pending', 'pending'), ('cancel', 'cancel')], default='pending', max_length=15)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_booking', to='accounts.customuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_booking', to='rooms.room')),
            ],
        ),
    ]
