# Generated by Django 4.0.6 on 2022-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online Pay'), ('offline', 'Offline Pay')], default='offline', max_length=15, null=True),
        ),
    ]
