# Generated by Django 4.0.6 on 2022-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_review_date_alter_review_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_rooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
