# Generated by Django 3.2.13 on 2022-07-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_certificate_customuser_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='photo',
            new_name='certificate',
        ),
    ]
